- hosts: prod-server
  become: true
  tasks:
  - name: update cache
    apt: 
     update_cache: yes

  - name: install docker
    apt:
     pkg: docker.io
     state: present

  - name: start docker service
    service:
       name: docker
       state: started
       enabled: true

  - name: deploy to prod-server
    command: docker run -itd -p 8083:8083 parulgupta6/medicure_new:2.0
